### PR TITLE
Fixed dependency on datauri.

### PR DESCRIPTION
**Pull request by seize-the-dave**

### CODE REVIEW

**Comment by oosterholt** [comment]
+1 for this PR because of the "Warning: Cannot call a class as a function" issue caused by datauri 1.0.0-alpha.4

**Comment by ericbeijer** [comment]
+1

"Warning: Cannot call a class as a function"

**Comment by heldr** [comment]
Gonna write a work around for datauri package, besides the fact it's a [major and alpha update](http://semver.org/) and for better compatibility, package.json must not have >= 0.1.

**Comment by heldr** [comment]
Uhm...I'm using ES6 Classes over Babel for datauri 1.0. In order to make it work, I need tor rewrite everything as function again, which is not the idea for the next release.

See old:
https://github.com/heldr/datauri/blob/master/lib/datauri/module.js

VS new:
https://github.com/heldr/datauri/blob/1b/src/datauri/module.js

**My suggestion:**
Fork this project with the version fix and npm publish it.

or ``rm -rf node_modules/grunt-data-uri && npm i -D datauri@0.8.0 && npm i``

in NPM 3 ``rm -rf node_modules/datauri && npm i -D datauri@0.8.0 && npm i``

**Comment by gionkunz** [comment]
+1

**Comment by heldr** [comment]
+1

**Comment by seize-the-dave** [comment]
Looks like @ahomu has committed an equivalent fix, so I'm going to close this.

**Comment by heldr** [comment]
cool! :smile:

**Comment by ahomu** [comment]
:+1:

**Pull request closed without merging**
